package refunds

import "time"

type CreateRefundRequest struct {
	Transaction  string `json:"transaction"`
	Amount       int64  `json:"amount"`
	Currency     string `json:"currency"`
	CustomerNote string `json:"customer_note"`
	MerchantNote string `json:"merchant_note"`
}
type CreateRefundResponse struct {
	Transaction    []interface{} `json:"transaction"`
	Integration    int           `json:"integration"`
	DeductedAmount int           `json:"deducted_amount"`
	Channel        interface{}   `json:"channel"`
	MerchantNote   string        `json:"merchant_note"`
	CustomerNote   string        `json:"customer_note"`
	Status         string        `json:"status"`
	RefundedBy     string        `json:"refunded_by"`
	ExpectedAt     time.Time     `json:"expected_at"`
	Currency       string        `json:"currency"`
	Domain         string        `json:"domain"`
	Amount         int           `json:"amount"`
	FullyDeducted  bool          `json:"fully_deducted"`
	ID             int           `json:"id"`
	CreatedAt      time.Time     `json:"createdAt"`
	UpdatedAt      time.Time     `json:"updatedAt"`
}

type AutoGenerated struct {
	Status  bool   `json:"status"`
	Message string `json:"message"`
	Data    struct {
		Transaction    []interface{} `json:"transaction"`
		Integration    int           `json:"integration"`
		DeductedAmount int           `json:"deducted_amount"`
		Channel        interface{}   `json:"channel"`
		MerchantNote   string        `json:"merchant_note"`
		CustomerNote   string        `json:"customer_note"`
		Status         string        `json:"status"`
		RefundedBy     string        `json:"refunded_by"`
		ExpectedAt     time.Time     `json:"expected_at"`
		Currency       string        `json:"currency"`
		Domain         string        `json:"domain"`
		Amount         int           `json:"amount"`
		FullyDeducted  bool          `json:"fully_deducted"`
		ID             int           `json:"id"`
		CreatedAt      time.Time     `json:"createdAt"`
		UpdatedAt      time.Time     `json:"updatedAt"`
	} `json:"data"`
}
