package refunds

import "time"

type CreateRefundRequest struct {
	Transaction  string `json:"transaction"`
	Amount       int64  `json:"amount"`
	Currency     string `json:"currency"`
	CustomerNote string `json:"customer_note"`
	MerchantNote string `json:"merchant_note"`
}
type CreateRefundResponse struct {
	Transaction    []interface{} `json:"transaction"`
	Integration    int           `json:"integration"`
	DeductedAmount int           `json:"deducted_amount"`
	Channel        interface{}   `json:"channel"`
	MerchantNote   string        `json:"merchant_note"`
	CustomerNote   string        `json:"customer_note"`
	Status         string        `json:"status"`
	RefundedBy     string        `json:"refunded_by"`
	ExpectedAt     time.Time     `json:"expected_at"`
	Currency       string        `json:"currency"`
	Domain         string        `json:"domain"`
	Amount         int           `json:"amount"`
	FullyDeducted  bool          `json:"fully_deducted"`
	ID             int           `json:"id"`
	CreatedAt      time.Time     `json:"createdAt"`
	UpdatedAt      time.Time     `json:"updatedAt"`
}

type AutoGenerated struct {
	Status  bool   `json:"status"`
	Message string `json:"message"`
	Data    struct {
		Transaction    []interface{} `json:"transaction"`
		Integration    int           `json:"integration"`
		DeductedAmount int           `json:"deducted_amount"`
		Channel        interface{}   `json:"channel"`
		MerchantNote   string        `json:"merchant_note"`
		CustomerNote   string        `json:"customer_note"`
		Status         string        `json:"status"`
		RefundedBy     string        `json:"refunded_by"`
		ExpectedAt     time.Time     `json:"expected_at"`
		Currency       string        `json:"currency"`
		Domain         string        `json:"domain"`
		Amount         int           `json:"amount"`
		FullyDeducted  bool          `json:"fully_deducted"`
		ID             int           `json:"id"`
		CreatedAt      time.Time     `json:"createdAt"`
		UpdatedAt      time.Time     `json:"updatedAt"`
	} `json:"data"`
}

type Refund struct {
	Integration          int         `json:"integration"`
	Transaction          int64       `json:"transaction"`
	Dispute              interface{} `json:"dispute"`
	Settlement           interface{} `json:"settlement"`
	ID                   int         `json:"id"`
	Domain               string      `json:"domain"`
	Currency             string      `json:"currency"`
	Amount               int         `json:"amount"`
	Status               string      `json:"status"`
	RefundedAt           interface{} `json:"refunded_at"`
	RefundedBy           string      `json:"refunded_by"`
	CustomerNote         string      `json:"customer_note"`
	MerchantNote         string      `json:"merchant_note"`
	DeductedAmount       int         `json:"deducted_amount"`
	FullyDeducted        int         `json:"fully_deducted"`
	CreatedAt            time.Time   `json:"createdAt"`
	BankReference        interface{} `json:"bank_reference"`
	TransactionReference string      `json:"transaction_reference"`
	Reason               string      `json:"reason"`
	Customer             struct {
		ID                       int         `json:"id"`
		FirstName                string      `json:"first_name"`
		LastName                 string      `json:"last_name"`
		Email                    string      `json:"email"`
		CustomerCode             string      `json:"customer_code"`
		Phone                    string      `json:"phone"`
		Metadata                 interface{} `json:"metadata"`
		RiskAction               string      `json:"risk_action"`
		InternationalFormatPhone interface{} `json:"international_format_phone"`
	} `json:"customer"`
	RefundType           string      `json:"refund_type"`
	TransactionAmount    int         `json:"transaction_amount"`
	InitiatedBy          string      `json:"initiated_by"`
	RefundChannel        string      `json:"refund_channel"`
	SessionID            interface{} `json:"session_id"`
	CollectAccountNumber bool        `json:"collect_account_number"`
}
